version: 2
jobs:
  build:
    docker:
      - image: node:10-alpine
    steps:
      - checkout
      - run:
          name: Install `ca-certificates`
          command: apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: node:10-alpine
    steps:
      - checkout
      - run:
          name: Build
          command: npm run build
      - run:
          name: Test and Codecov
          command: npm run codecov
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
          requires:
            - build
