version: 2.0
jobs:
  build:
    docker:
      - image: node:10-alpine
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install `ca-certificates`
          command: apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: npm run build
      - run:
          name: Codecov
          command: npm run codecov
